### ISSUE TITLE
Settling down with a caravan (some of it riding animals) crashes the game

### ISSUE THREAD

**Issue by Zemogiter** [rheirman/GiddyUpCore#20]
Creating a new save works fine. It's when you send a caravan from an existing base to form a new one that crashes the game.
[error.log](https://github.com/rheirman/GiddyUpCore/files/3316767/error.log)
[output_log.txt](https://github.com/rheirman/GiddyUpCore/files/3316768/output_log.txt)
https://www.mediafire.com/file/tb4fg891csiuscz/crash.dmp/file

https://www.mediafire.com/file/jsxsgq863d39vnd/Wasbutunt_Confederation.rws/file

**Comment by rheirman** [comment]
I fixed this in the latest release. Thanks for your report!
